version: "3"

services:
  database:
    container_name: postgres
    image: "postgres:12.10"
    env_file: ./backend/.env
    ports:
      - 5432:5432
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_URL=http://localhost:3001
  backend:
    build: ./backend
    container_name: backend
    ports:
      - 3001:3001
