insert into Service (id, professional_id, name, starting_price, estimated_time) values (1, 95, 'Bigode', 152.01, 86);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (2, 48, 'Barba', 122.46, 76);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (3, 98, 'Cabelo (tesoura)', 193.82, 52);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (4, 56, 'Barba', 256.12, 72);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (5, 3, 'Cabelo (máquina)', 248.57, 85);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (6, 81, 'Cabelo (tesoura)', 90.64, 49);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (7, 13, 'Bigode', 222.47, 57);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (8, 71, 'Design de Sobrancelhas', 271.5, 61);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (9, 100, 'Bigode', 275.53, 72);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (10, 58, 'Bigode', 151.39, 87);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (11, 24, 'Barba', 110.46, 83);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (12, 43, 'Design de Sobrancelhas', 75.52, 79);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (13, 78, 'Cabelo (máquina)', 276.65, 68);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (14, 60, 'Bigode', 80.72, 39);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (15, 91, 'Barba', 134.95, 48);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (16, 45, 'Design de Sobrancelhas', 113.0, 37);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (17, 94, 'Cabelo (máquina)', 293.75, 35);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (18, 19, 'Cabelo (tesoura)', 298.66, 79);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (19, 69, 'Cabelo (máquina)', 283.88, 38);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (20, 40, 'Barba', 57.52, 42);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (21, 63, 'Barba', 210.99, 76);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (22, 14, 'Barba', 83.5, 34);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (23, 49, 'Design de Sobrancelhas', 161.5, 31);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (24, 39, 'Tingir Cabelo', 277.38, 72);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (25, 55, 'Bigode', 199.87, 34);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (26, 47, 'Tingir Cabelo', 236.62, 83);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (27, 59, 'Design de Sobrancelhas', 176.23, 89);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (28, 73, 'Design de Sobrancelhas', 175.07, 62);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (29, 56, 'Bigode', 183.81, 86);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (30, 37, 'Cabelo (tesoura)', 78.95, 54);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (31, 27, 'Bigode', 139.88, 42);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (32, 8, 'Tingir Cabelo', 280.67, 74);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (33, 74, 'Bigode', 111.89, 88);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (34, 29, 'Barba', 59.34, 68);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (35, 40, 'Bigode', 210.63, 40);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (36, 5, 'Barba', 78.37, 81);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (37, 13, 'Cabelo (tesoura)', 49.5, 76);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (38, 8, 'Bigode', 131.88, 31);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (39, 59, 'Bigode', 126.41, 44);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (40, 43, 'Tingir Cabelo', 221.88, 71);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (41, 22, 'Design de Sobrancelhas', 192.57, 30);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (42, 89, 'Design de Sobrancelhas', 246.76, 68);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (43, 10, 'Cabelo (tesoura)', 282.71, 62);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (44, 45, 'Design de Sobrancelhas', 121.96, 43);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (45, 60, 'Tingir Cabelo', 185.86, 64);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (46, 54, 'Design de Sobrancelhas', 181.93, 75);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (47, 80, 'Bigode', 287.36, 88);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (48, 81, 'Bigode', 73.69, 73);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (49, 85, 'Bigode', 263.03, 59);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (50, 85, 'Design de Sobrancelhas', 125.42, 69);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (51, 72, 'Bigode', 192.55, 45);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (52, 18, 'Barba', 152.13, 87);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (53, 86, 'Tingir Cabelo', 260.91, 33);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (54, 91, 'Barba', 287.4, 88);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (55, 94, 'Barba', 73.35, 83);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (56, 90, 'Tingir Cabelo', 41.87, 88);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (57, 51, 'Barba', 243.86, 60);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (58, 52, 'Cabelo (máquina)', 247.27, 64);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (59, 18, 'Design de Sobrancelhas', 132.11, 45);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (60, 95, 'Design de Sobrancelhas', 192.11, 36);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (61, 35, 'Cabelo (máquina)', 49.1, 79);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (62, 49, 'Barba', 121.09, 33);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (63, 4, 'Design de Sobrancelhas', 226.94, 43);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (64, 7, 'Cabelo (tesoura)', 282.08, 39);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (65, 70, 'Tingir Cabelo', 87.61, 47);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (66, 16, 'Barba', 272.27, 84);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (67, 27, 'Design de Sobrancelhas', 35.28, 51);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (68, 78, 'Design de Sobrancelhas', 96.86, 54);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (69, 41, 'Tingir Cabelo', 153.78, 45);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (70, 99, 'Cabelo (tesoura)', 81.17, 78);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (71, 20, 'Tingir Cabelo', 237.33, 68);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (72, 36, 'Bigode', 138.01, 77);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (73, 10, 'Barba', 100.12, 87);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (74, 55, 'Cabelo (tesoura)', 93.26, 32);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (75, 14, 'Barba', 80.36, 48);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (76, 46, 'Cabelo (máquina)', 288.1, 69);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (77, 64, 'Cabelo (tesoura)', 146.63, 83);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (78, 66, 'Cabelo (tesoura)', 112.01, 79);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (79, 21, 'Cabelo (máquina)', 149.06, 72);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (80, 30, 'Cabelo (máquina)', 182.89, 61);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (81, 43, 'Design de Sobrancelhas', 191.26, 88);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (82, 53, 'Cabelo (máquina)', 129.2, 31);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (83, 38, 'Barba', 294.95, 65);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (84, 94, 'Barba', 93.05, 59);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (85, 69, 'Cabelo (tesoura)', 36.45, 81);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (86, 67, 'Design de Sobrancelhas', 120.67, 85);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (87, 87, 'Barba', 49.32, 71);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (88, 51, 'Design de Sobrancelhas', 249.61, 36);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (89, 14, 'Barba', 185.22, 69);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (90, 55, 'Cabelo (máquina)', 147.0, 77);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (91, 89, 'Cabelo (máquina)', 232.11, 66);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (92, 61, 'Barba', 103.75, 48);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (93, 3, 'Tingir Cabelo', 253.57, 62);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (94, 37, 'Cabelo (máquina)', 135.2, 39);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (95, 81, 'Cabelo (máquina)', 110.24, 58);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (96, 65, 'Barba', 92.84, 75);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (97, 26, 'Design de Sobrancelhas', 50.42, 30);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (98, 7, 'Barba', 262.42, 77);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (99, 40, 'Design de Sobrancelhas', 107.73, 48);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (100, 1, 'Cabelo (máquina)', 294.7, 58);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (101, 99, 'Tingir Cabelo', 50.32, 41);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (102, 12, 'Design de Sobrancelhas', 230.03, 83);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (103, 40, 'Barba', 32.74, 48);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (104, 51, 'Cabelo (tesoura)', 88.76, 71);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (105, 71, 'Design de Sobrancelhas', 247.58, 56);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (106, 46, 'Cabelo (tesoura)', 131.28, 77);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (107, 71, 'Barba', 68.65, 62);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (108, 11, 'Cabelo (máquina)', 167.15, 63);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (109, 34, 'Barba', 244.55, 36);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (110, 88, 'Design de Sobrancelhas', 250.42, 33);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (111, 97, 'Design de Sobrancelhas', 290.16, 66);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (112, 7, 'Cabelo (tesoura)', 66.06, 61);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (113, 8, 'Cabelo (tesoura)', 34.68, 36);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (114, 99, 'Cabelo (tesoura)', 144.44, 90);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (115, 38, 'Bigode', 55.91, 65);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (116, 12, 'Cabelo (tesoura)', 127.07, 40);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (117, 89, 'Bigode', 233.67, 54);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (118, 60, 'Cabelo (tesoura)', 119.36, 88);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (119, 73, 'Tingir Cabelo', 71.81, 64);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (120, 70, 'Tingir Cabelo', 190.02, 42);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (121, 89, 'Tingir Cabelo', 160.5, 56);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (122, 8, 'Barba', 117.46, 67);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (123, 89, 'Cabelo (máquina)', 151.94, 60);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (124, 31, 'Tingir Cabelo', 43.12, 71);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (125, 75, 'Bigode', 39.68, 83);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (126, 75, 'Cabelo (máquina)', 213.88, 46);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (127, 13, 'Tingir Cabelo', 267.83, 69);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (128, 14, 'Cabelo (máquina)', 105.91, 46);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (129, 88, 'Tingir Cabelo', 261.25, 64);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (130, 33, 'Cabelo (tesoura)', 70.87, 36);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (131, 69, 'Cabelo (máquina)', 127.66, 63);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (132, 17, 'Design de Sobrancelhas', 185.02, 80);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (133, 99, 'Cabelo (máquina)', 180.28, 37);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (134, 91, 'Barba', 156.3, 46);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (135, 74, 'Tingir Cabelo', 221.21, 40);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (136, 16, 'Bigode', 33.37, 62);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (137, 72, 'Design de Sobrancelhas', 61.11, 72);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (138, 50, 'Barba', 219.7, 77);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (139, 4, 'Tingir Cabelo', 269.3, 88);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (140, 6, 'Design de Sobrancelhas', 298.78, 77);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (141, 41, 'Bigode', 190.7, 68);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (142, 23, 'Design de Sobrancelhas', 213.7, 58);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (143, 93, 'Cabelo (máquina)', 223.68, 73);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (144, 74, 'Cabelo (máquina)', 133.7, 82);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (145, 16, 'Cabelo (tesoura)', 68.59, 90);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (146, 36, 'Cabelo (máquina)', 247.63, 58);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (147, 9, 'Cabelo (tesoura)', 277.52, 78);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (148, 55, 'Tingir Cabelo', 162.5, 70);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (149, 43, 'Barba', 181.27, 75);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (150, 93, 'Tingir Cabelo', 222.1, 39);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (151, 27, 'Barba', 192.93, 81);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (152, 58, 'Cabelo (tesoura)', 177.49, 57);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (153, 72, 'Cabelo (máquina)', 190.55, 75);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (154, 83, 'Barba', 103.85, 51);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (155, 70, 'Cabelo (tesoura)', 127.71, 60);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (156, 3, 'Bigode', 229.4, 53);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (157, 65, 'Design de Sobrancelhas', 243.1, 34);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (158, 87, 'Cabelo (tesoura)', 228.57, 69);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (159, 49, 'Barba', 104.11, 82);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (160, 72, 'Cabelo (máquina)', 223.21, 31);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (161, 14, 'Barba', 115.28, 56);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (162, 60, 'Barba', 45.41, 44);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (163, 46, 'Barba', 282.0, 64);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (164, 53, 'Design de Sobrancelhas', 258.08, 76);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (165, 94, 'Cabelo (máquina)', 231.89, 88);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (166, 67, 'Cabelo (tesoura)', 286.22, 70);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (167, 91, 'Barba', 99.2, 86);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (168, 82, 'Cabelo (tesoura)', 139.68, 66);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (169, 98, 'Cabelo (máquina)', 218.16, 35);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (170, 1, 'Bigode', 47.79, 64);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (171, 13, 'Tingir Cabelo', 38.09, 57);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (172, 50, 'Design de Sobrancelhas', 85.83, 60);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (173, 98, 'Tingir Cabelo', 156.66, 50);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (174, 63, 'Bigode', 176.51, 79);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (175, 69, 'Barba', 95.73, 82);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (176, 33, 'Bigode', 181.97, 83);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (177, 61, 'Barba', 182.81, 45);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (178, 10, 'Bigode', 242.14, 49);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (179, 36, 'Cabelo (máquina)', 158.16, 47);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (180, 59, 'Tingir Cabelo', 33.58, 90);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (181, 23, 'Tingir Cabelo', 44.75, 60);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (182, 28, 'Cabelo (tesoura)', 51.15, 66);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (183, 75, 'Cabelo (tesoura)', 225.95, 33);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (184, 67, 'Cabelo (máquina)', 31.28, 49);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (185, 96, 'Design de Sobrancelhas', 111.24, 52);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (186, 29, 'Tingir Cabelo', 254.1, 49);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (187, 94, 'Cabelo (máquina)', 190.82, 45);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (188, 57, 'Barba', 194.49, 83);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (189, 36, 'Tingir Cabelo', 127.11, 66);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (190, 94, 'Cabelo (tesoura)', 180.97, 33);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (191, 89, 'Barba', 106.47, 77);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (192, 60, 'Cabelo (máquina)', 94.75, 41);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (193, 42, 'Bigode', 260.8, 58);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (194, 54, 'Design de Sobrancelhas', 259.67, 59);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (195, 42, 'Tingir Cabelo', 247.53, 62);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (196, 25, 'Design de Sobrancelhas', 111.61, 73);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (197, 68, 'Cabelo (máquina)', 274.72, 73);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (198, 10, 'Barba', 251.32, 38);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (199, 89, 'Barba', 125.41, 66);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (200, 37, 'Cabelo (tesoura)', 51.02, 43);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (201, 73, 'Design de Sobrancelhas', 298.96, 85);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (202, 87, 'Bigode', 111.0, 73);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (203, 75, 'Bigode', 87.18, 69);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (204, 89, 'Cabelo (máquina)', 223.5, 53);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (205, 16, 'Design de Sobrancelhas', 42.25, 36);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (206, 70, 'Bigode', 152.3, 75);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (207, 77, 'Barba', 56.38, 47);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (208, 86, 'Cabelo (tesoura)', 108.38, 45);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (209, 64, 'Barba', 192.72, 70);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (210, 57, 'Barba', 128.33, 31);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (211, 18, 'Cabelo (máquina)', 194.44, 76);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (212, 77, 'Cabelo (máquina)', 166.48, 50);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (213, 64, 'Design de Sobrancelhas', 222.86, 37);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (214, 60, 'Cabelo (tesoura)', 294.53, 77);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (215, 96, 'Cabelo (máquina)', 119.94, 41);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (216, 9, 'Cabelo (máquina)', 202.89, 46);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (217, 26, 'Cabelo (máquina)', 225.05, 88);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (218, 75, 'Design de Sobrancelhas', 273.19, 84);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (219, 57, 'Barba', 281.34, 66);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (220, 84, 'Design de Sobrancelhas', 138.47, 45);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (221, 40, 'Bigode', 210.64, 65);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (222, 60, 'Design de Sobrancelhas', 96.18, 58);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (223, 56, 'Bigode', 120.57, 53);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (224, 69, 'Barba', 131.7, 30);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (225, 34, 'Cabelo (tesoura)', 160.09, 43);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (226, 66, 'Barba', 115.59, 67);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (227, 73, 'Cabelo (máquina)', 286.84, 45);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (228, 88, 'Cabelo (tesoura)', 201.71, 49);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (229, 83, 'Cabelo (tesoura)', 116.99, 57);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (230, 53, 'Barba', 245.85, 64);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (231, 37, 'Design de Sobrancelhas', 206.74, 37);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (232, 44, 'Cabelo (tesoura)', 46.47, 75);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (233, 86, 'Tingir Cabelo', 272.82, 55);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (234, 32, 'Design de Sobrancelhas', 212.09, 51);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (235, 94, 'Barba', 264.86, 57);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (236, 27, 'Barba', 266.79, 56);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (237, 36, 'Cabelo (máquina)', 290.73, 62);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (238, 29, 'Tingir Cabelo', 129.6, 41);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (239, 13, 'Cabelo (tesoura)', 198.66, 73);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (240, 46, 'Bigode', 170.14, 52);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (241, 18, 'Cabelo (tesoura)', 211.29, 49);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (242, 98, 'Barba', 60.5, 74);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (243, 18, 'Tingir Cabelo', 89.96, 84);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (244, 17, 'Tingir Cabelo', 90.74, 30);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (245, 80, 'Bigode', 193.22, 71);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (246, 58, 'Tingir Cabelo', 208.17, 49);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (247, 72, 'Design de Sobrancelhas', 153.44, 73);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (248, 19, 'Bigode', 59.13, 85);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (249, 91, 'Design de Sobrancelhas', 83.58, 32);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (250, 47, 'Cabelo (máquina)', 224.1, 45);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (251, 95, 'Bigode', 160.44, 64);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (252, 47, 'Tingir Cabelo', 220.22, 46);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (253, 27, 'Bigode', 160.02, 39);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (254, 5, 'Barba', 132.4, 50);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (255, 34, 'Tingir Cabelo', 43.42, 63);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (256, 72, 'Bigode', 271.09, 69);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (257, 3, 'Cabelo (máquina)', 115.24, 69);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (258, 70, 'Design de Sobrancelhas', 108.44, 44);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (259, 13, 'Tingir Cabelo', 277.82, 62);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (260, 61, 'Barba', 57.97, 32);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (261, 55, 'Cabelo (máquina)', 209.46, 51);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (262, 17, 'Bigode', 91.79, 77);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (263, 87, 'Design de Sobrancelhas', 182.8, 42);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (264, 9, 'Cabelo (tesoura)', 200.3, 55);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (265, 74, 'Barba', 157.31, 62);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (266, 66, 'Tingir Cabelo', 224.33, 33);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (267, 4, 'Tingir Cabelo', 91.77, 50);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (268, 95, 'Tingir Cabelo', 55.67, 86);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (269, 98, 'Barba', 97.81, 74);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (270, 25, 'Cabelo (tesoura)', 140.83, 34);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (271, 59, 'Cabelo (máquina)', 35.69, 64);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (272, 99, 'Barba', 151.89, 84);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (273, 84, 'Design de Sobrancelhas', 117.25, 73);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (274, 39, 'Cabelo (tesoura)', 140.45, 67);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (275, 19, 'Barba', 109.17, 63);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (276, 51, 'Cabelo (máquina)', 177.7, 51);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (277, 66, 'Cabelo (máquina)', 133.82, 43);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (278, 69, 'Cabelo (máquina)', 226.21, 81);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (279, 55, 'Barba', 110.09, 30);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (280, 11, 'Barba', 155.68, 33);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (281, 69, 'Cabelo (máquina)', 72.69, 85);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (282, 39, 'Barba', 114.66, 71);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (283, 89, 'Bigode', 33.28, 83);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (284, 4, 'Barba', 292.99, 41);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (285, 20, 'Cabelo (máquina)', 164.2, 86);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (286, 32, 'Barba', 119.06, 36);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (287, 98, 'Tingir Cabelo', 128.06, 45);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (288, 15, 'Cabelo (máquina)', 50.82, 40);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (289, 57, 'Barba', 48.9, 50);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (290, 11, 'Tingir Cabelo', 140.24, 41);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (291, 26, 'Cabelo (tesoura)', 260.31, 41);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (292, 57, 'Design de Sobrancelhas', 272.69, 66);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (293, 96, 'Cabelo (tesoura)', 70.45, 52);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (294, 14, 'Cabelo (tesoura)', 30.02, 88);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (295, 71, 'Bigode', 133.19, 32);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (296, 53, 'Cabelo (tesoura)', 128.37, 51);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (297, 28, 'Design de Sobrancelhas', 293.22, 89);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (298, 9, 'Barba', 225.87, 31);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (299, 90, 'Bigode', 260.41, 49);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (300, 12, 'Design de Sobrancelhas', 201.46, 38);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (301, 78, 'Barba', 85.42, 59);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (302, 13, 'Cabelo (tesoura)', 293.73, 66);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (303, 71, 'Tingir Cabelo', 164.22, 54);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (304, 1, 'Bigode', 49.99, 74);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (305, 44, 'Cabelo (máquina)', 284.2, 52);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (306, 23, 'Barba', 238.33, 76);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (307, 28, 'Barba', 134.83, 48);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (308, 21, 'Barba', 153.29, 64);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (309, 94, 'Barba', 143.62, 56);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (310, 96, 'Design de Sobrancelhas', 270.45, 32);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (311, 66, 'Tingir Cabelo', 230.16, 68);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (312, 88, 'Cabelo (máquina)', 32.87, 37);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (313, 62, 'Barba', 135.16, 69);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (314, 69, 'Cabelo (máquina)', 229.65, 37);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (315, 59, 'Bigode', 99.74, 90);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (316, 62, 'Cabelo (tesoura)', 142.93, 34);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (317, 5, 'Bigode', 119.49, 60);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (318, 4, 'Barba', 53.8, 79);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (319, 2, 'Barba', 291.01, 87);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (320, 29, 'Barba', 78.17, 88);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (321, 90, 'Tingir Cabelo', 269.82, 60);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (322, 70, 'Cabelo (máquina)', 58.33, 74);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (323, 82, 'Tingir Cabelo', 202.54, 64);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (324, 86, 'Bigode', 178.64, 50);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (325, 51, 'Tingir Cabelo', 106.12, 46);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (326, 63, 'Cabelo (máquina)', 169.21, 34);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (327, 31, 'Bigode', 54.79, 69);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (328, 75, 'Tingir Cabelo', 117.09, 31);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (329, 70, 'Cabelo (máquina)', 123.6, 47);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (330, 31, 'Bigode', 288.85, 55);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (331, 68, 'Cabelo (tesoura)', 218.99, 52);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (332, 91, 'Barba', 257.2, 89);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (333, 4, 'Cabelo (máquina)', 74.48, 45);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (334, 88, 'Cabelo (tesoura)', 167.86, 61);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (335, 100, 'Cabelo (tesoura)', 196.02, 42);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (336, 94, 'Cabelo (tesoura)', 86.05, 50);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (337, 88, 'Design de Sobrancelhas', 208.7, 40);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (338, 90, 'Barba', 179.86, 70);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (339, 71, 'Cabelo (tesoura)', 156.88, 43);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (340, 79, 'Bigode', 238.89, 66);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (341, 51, 'Barba', 220.62, 41);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (342, 24, 'Barba', 62.42, 80);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (343, 31, 'Cabelo (máquina)', 37.04, 64);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (344, 35, 'Barba', 233.01, 34);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (345, 73, 'Bigode', 201.9, 80);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (346, 14, 'Barba', 90.46, 48);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (347, 53, 'Tingir Cabelo', 76.88, 64);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (348, 93, 'Cabelo (máquina)', 213.8, 38);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (349, 90, 'Tingir Cabelo', 170.65, 40);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (350, 8, 'Barba', 279.38, 77);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (351, 25, 'Design de Sobrancelhas', 114.95, 34);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (352, 100, 'Design de Sobrancelhas', 164.17, 73);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (353, 23, 'Barba', 45.28, 58);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (354, 50, 'Cabelo (máquina)', 124.92, 68);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (355, 93, 'Bigode', 195.48, 80);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (356, 50, 'Barba', 58.6, 57);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (357, 73, 'Cabelo (máquina)', 125.56, 47);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (358, 93, 'Cabelo (tesoura)', 282.89, 89);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (359, 86, 'Barba', 266.72, 61);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (360, 3, 'Barba', 156.72, 70);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (361, 17, 'Design de Sobrancelhas', 60.89, 82);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (362, 9, 'Cabelo (tesoura)', 226.02, 32);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (363, 79, 'Design de Sobrancelhas', 99.78, 78);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (364, 78, 'Tingir Cabelo', 233.08, 30);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (365, 28, 'Cabelo (tesoura)', 202.61, 44);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (366, 23, 'Design de Sobrancelhas', 150.36, 36);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (367, 12, 'Cabelo (máquina)', 166.93, 54);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (368, 96, 'Bigode', 168.62, 50);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (369, 60, 'Barba', 69.6, 33);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (370, 65, 'Design de Sobrancelhas', 57.18, 67);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (371, 86, 'Bigode', 250.04, 32);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (372, 48, 'Bigode', 31.67, 53);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (373, 15, 'Design de Sobrancelhas', 242.18, 85);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (374, 79, 'Cabelo (máquina)', 206.18, 80);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (375, 23, 'Design de Sobrancelhas', 80.4, 44);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (376, 1, 'Tingir Cabelo', 37.9, 75);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (377, 81, 'Barba', 34.97, 52);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (378, 71, 'Barba', 195.82, 72);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (379, 70, 'Cabelo (tesoura)', 133.8, 40);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (380, 46, 'Barba', 37.98, 53);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (381, 33, 'Design de Sobrancelhas', 114.95, 71);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (382, 5, 'Barba', 194.72, 69);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (383, 91, 'Barba', 179.63, 72);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (384, 81, 'Design de Sobrancelhas', 71.12, 49);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (385, 47, 'Tingir Cabelo', 281.23, 32);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (386, 86, 'Cabelo (máquina)', 219.4, 66);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (387, 55, 'Barba', 111.06, 45);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (388, 32, 'Design de Sobrancelhas', 243.36, 84);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (389, 71, 'Tingir Cabelo', 97.3, 89);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (390, 23, 'Bigode', 79.36, 77);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (391, 77, 'Cabelo (máquina)', 169.03, 75);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (392, 12, 'Bigode', 37.15, 90);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (393, 15, 'Tingir Cabelo', 134.51, 65);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (394, 45, 'Barba', 162.32, 47);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (395, 51, 'Barba', 202.34, 72);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (396, 12, 'Cabelo (tesoura)', 253.36, 68);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (397, 75, 'Bigode', 66.6, 60);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (398, 98, 'Design de Sobrancelhas', 170.25, 33);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (399, 10, 'Bigode', 113.93, 68);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (400, 88, 'Tingir Cabelo', 66.77, 75);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (401, 76, 'Bigode', 255.55, 77);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (402, 68, 'Cabelo (tesoura)', 88.22, 36);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (403, 80, 'Cabelo (tesoura)', 214.41, 85);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (404, 45, 'Cabelo (tesoura)', 43.94, 54);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (405, 50, 'Bigode', 70.31, 51);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (406, 40, 'Design de Sobrancelhas', 121.98, 84);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (407, 53, 'Tingir Cabelo', 75.5, 76);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (408, 47, 'Cabelo (máquina)', 152.86, 84);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (409, 52, 'Bigode', 151.9, 44);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (410, 54, 'Tingir Cabelo', 132.66, 80);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (411, 35, 'Design de Sobrancelhas', 193.29, 69);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (412, 12, 'Design de Sobrancelhas', 274.83, 38);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (413, 24, 'Tingir Cabelo', 298.73, 55);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (414, 44, 'Barba', 89.93, 78);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (415, 18, 'Cabelo (máquina)', 113.45, 31);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (416, 51, 'Cabelo (máquina)', 85.52, 43);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (417, 42, 'Barba', 183.77, 72);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (418, 71, 'Bigode', 64.76, 80);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (419, 94, 'Barba', 102.18, 34);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (420, 55, 'Tingir Cabelo', 258.71, 67);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (421, 9, 'Barba', 268.93, 68);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (422, 49, 'Tingir Cabelo', 167.14, 88);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (423, 37, 'Tingir Cabelo', 48.31, 38);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (424, 54, 'Design de Sobrancelhas', 74.06, 52);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (425, 14, 'Bigode', 74.82, 44);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (426, 95, 'Design de Sobrancelhas', 163.27, 61);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (427, 87, 'Cabelo (tesoura)', 95.39, 39);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (428, 32, 'Cabelo (tesoura)', 248.83, 30);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (429, 82, 'Tingir Cabelo', 130.57, 46);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (430, 85, 'Cabelo (tesoura)', 58.48, 42);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (431, 27, 'Barba', 239.51, 86);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (432, 94, 'Bigode', 30.43, 84);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (433, 78, 'Tingir Cabelo', 260.74, 87);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (434, 73, 'Bigode', 225.26, 44);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (435, 47, 'Barba', 255.55, 79);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (436, 97, 'Cabelo (tesoura)', 173.59, 67);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (437, 81, 'Cabelo (máquina)', 270.67, 87);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (438, 44, 'Cabelo (máquina)', 69.64, 52);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (439, 24, 'Design de Sobrancelhas', 115.61, 59);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (440, 41, 'Cabelo (máquina)', 152.82, 45);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (441, 6, 'Bigode', 285.68, 70);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (442, 2, 'Bigode', 67.6, 90);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (443, 60, 'Bigode', 259.24, 43);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (444, 57, 'Cabelo (tesoura)', 229.89, 73);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (445, 83, 'Tingir Cabelo', 103.33, 45);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (446, 30, 'Cabelo (máquina)', 188.17, 89);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (447, 82, 'Cabelo (máquina)', 293.78, 74);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (448, 25, 'Bigode', 266.39, 86);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (449, 95, 'Cabelo (máquina)', 289.41, 37);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (450, 85, 'Tingir Cabelo', 103.83, 33);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (451, 93, 'Cabelo (máquina)', 221.9, 73);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (452, 95, 'Barba', 255.67, 60);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (453, 51, 'Design de Sobrancelhas', 259.49, 46);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (454, 32, 'Cabelo (máquina)', 223.01, 56);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (455, 1, 'Tingir Cabelo', 129.12, 90);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (456, 17, 'Cabelo (máquina)', 146.93, 44);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (457, 6, 'Cabelo (máquina)', 189.34, 63);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (458, 68, 'Design de Sobrancelhas', 191.97, 57);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (459, 85, 'Bigode', 276.74, 65);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (460, 57, 'Cabelo (tesoura)', 181.65, 38);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (461, 84, 'Bigode', 97.22, 48);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (462, 64, 'Barba', 261.58, 71);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (463, 94, 'Design de Sobrancelhas', 139.42, 81);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (464, 17, 'Cabelo (máquina)', 70.07, 32);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (465, 55, 'Barba', 247.59, 54);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (466, 2, 'Barba', 87.74, 57);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (467, 22, 'Tingir Cabelo', 175.73, 44);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (468, 70, 'Tingir Cabelo', 287.47, 77);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (469, 56, 'Bigode', 217.49, 32);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (470, 7, 'Cabelo (máquina)', 75.22, 31);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (471, 2, 'Design de Sobrancelhas', 206.25, 59);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (472, 83, 'Design de Sobrancelhas', 177.03, 57);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (473, 37, 'Cabelo (tesoura)', 110.41, 42);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (474, 25, 'Barba', 104.38, 79);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (475, 100, 'Tingir Cabelo', 188.0, 57);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (476, 21, 'Cabelo (tesoura)', 161.18, 89);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (477, 83, 'Bigode', 47.91, 78);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (478, 20, 'Design de Sobrancelhas', 227.57, 39);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (479, 4, 'Barba', 160.67, 76);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (480, 63, 'Tingir Cabelo', 142.79, 32);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (481, 21, 'Cabelo (máquina)', 278.16, 37);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (482, 30, 'Cabelo (tesoura)', 118.51, 62);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (483, 32, 'Cabelo (tesoura)', 93.45, 65);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (484, 22, 'Barba', 113.81, 69);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (485, 12, 'Tingir Cabelo', 98.61, 55);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (486, 84, 'Cabelo (máquina)', 59.77, 55);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (487, 48, 'Cabelo (máquina)', 81.01, 52);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (488, 18, 'Cabelo (máquina)', 53.73, 56);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (489, 82, 'Design de Sobrancelhas', 259.06, 58);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (490, 61, 'Bigode', 63.99, 78);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (491, 24, 'Tingir Cabelo', 260.42, 50);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (492, 39, 'Cabelo (tesoura)', 298.98, 65);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (493, 64, 'Barba', 53.57, 51);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (494, 8, 'Tingir Cabelo', 173.26, 52);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (495, 51, 'Tingir Cabelo', 243.3, 75);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (496, 72, 'Bigode', 206.77, 43);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (497, 96, 'Cabelo (máquina)', 102.44, 82);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (498, 8, 'Bigode', 115.06, 60);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (499, 78, 'Tingir Cabelo', 68.56, 70);
insert into Service (id, professional_id, name, starting_price, estimated_time) values (500, 65, 'Cabelo (tesoura)', 41.58, 70);
