insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (1, 1, null, 'Pawling', '4907', 'Center', 'Belém');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (2, 2, 3, 'Johnson', '3', null, 'Curitiba');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (3, 4, null, 'Bartillon', '5750', 'Pass', 'Natal');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (4, 5, null, 'Steensland', '419', null, 'Boa Vista');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (5, 6, 7, 'Kedzie', '57153', null, 'Porto Alegre');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (6, 8, null, 'Cherokee', '81', null, 'Belo Horizonte');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (7, 9, 10, 'Oriole', '3050', null, 'São Paulo');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (8, 11, 12, 'Center', '447', null, 'Recife');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (9, 13, 14, 'Alpine', '50', null, 'São Luís');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (10, 15, 16, 'Paget', '3892', null, 'Natal');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (11, 17, 18, 'Park Meadow', '067', null, 'Cuiabá');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (12, 19, null, 'Annamark', '3', null, 'Porto Velho');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (13, 20, 21, 'Graceland', '3', null, 'Maceió');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (14, 22, 23, 'Reindahl', '812', 'Plaza', 'Belo Horizonte');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (15, 24, 25, 'Toban', '1', null, 'Macapá');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (16, 26, null, 'Petterle', '1', 'Pass', 'Goiânia');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (17, 27, 28, 'Jenifer', '00', null, 'Fortaleza');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (18, 29, 30, 'Bayside', '8', null, 'Macapá');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (19, 31, 32, 'Barnett', '77', null, 'Salvador');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (20, 33, 34, 'Shoshone', '7', null, 'São Paulo');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (21, 35, null, 'Sage', '1552', null, 'Maceió');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (22, 36, 37, 'Grasskamp', '268', null, 'Cuiabá');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (23, 38, 39, 'Waxwing', '4365', null, 'São Luís');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (24, 40, 41, 'Lakeland', '759', null, 'Manaus');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (25, 42, 43, 'Continental', '17324', null, 'Cuiabá');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (26, 44, 45, 'Russell', '3', null, 'Maceió');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (27, 46, null, 'Ronald Regan', '551', null, 'Vitória');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (28, 47, null, 'Fulton', '703', null, 'Cuiabá');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (29, 48, 49, 'Golf View', '18', null, 'Porto Alegre');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (30, 50, 51, 'Monument', '2', null, 'Vitória');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (31, 52, 53, 'Grayhawk', '5', 'Road', 'São Luís');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (32, 54, null, 'Mallard', '54', 'Parkway', 'Belo Horizonte');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (33, 55, 56, 'Charing Cross', '5898', null, 'Curitiba');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (34, 57, 58, 'Carberry', '8462', null, 'Rio Branco');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (35, 59, 60, 'Monterey', '70073', null, 'Natal');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (36, 61, 62, 'Loomis', '51', null, 'Goiânia');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (37, 63, 64, 'Sunfield', '62528', null, 'Vitória');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (38, 65, 66, 'Fuller', '32', null, 'Boa Vista');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (39, 67, 68, 'Bowman', '4', null, 'João Pessoa');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (40, 69, 70, 'Oriole', '4', null, 'Belém');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (41, 71, 72, 'Arapahoe', '6', null, 'Maceió');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (42, 73, null, 'Bunting', '20797', null, 'Belo Horizonte');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (43, 74, 75, 'Fulton', '6', null, 'Teresina');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (44, 76, null, '2nd', '0849', null, 'Recife');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (45, 77, 78, 'Steensland', '1', null, 'Natal');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (46, 79, 80, 'Del Mar', '9', 'Road', 'Recife');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (47, 81, 82, 'Hanover', '82807', null, 'Rio de Janeiro');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (48, 83, null, 'Saint Paul', '17825', null, 'São Luís');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (49, 84, 85, 'Linden', '00', null, 'Cuiabá');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (50, 86, null, 'Sachs', '38', null, 'São Luís');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (51, 87, null, 'Pierstorff', '4382', null, 'Belo Horizonte');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (52, 88, null, 'Sutteridge', '95625', null, 'Belo Horizonte');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (53, 89, 90, 'Butternut', '085', null, 'Porto Velho');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (54, 91, 92, 'Forest Dale', '93', null, 'Rio Branco');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (55, 93, 94, 'Dexter', '69', null, 'Brasília');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (56, 95, 96, 'Sloan', '0564', 'Place', 'Manaus');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (57, 97, 98, 'Warbler', '4', null, 'Fortaleza');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (58, 99, null, 'Arapahoe', '6513', null, 'Recife');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (59, 100, 101, 'Arapahoe', '33276', 'Hill', 'Vitória');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (60, 102, 103, 'Brickson Park', '4197', null, 'Macapá');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (61, 104, null, 'Melvin', '60', null, 'Teresina');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (62, 105, 106, 'Gerald', '78', null, 'Boa Vista');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (63, 107, null, 'Novick', '4061', null, 'Belo Horizonte');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (64, 108, null, 'Sunnyside', '233', 'Road', 'Palmas');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (65, 109, 110, '7th', '9427', 'Parkway', 'João Pessoa');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (66, 111, 112, 'Orin', '47', null, 'João Pessoa');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (67, 113, null, 'Michigan', '72394', 'Park', 'Manaus');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (68, 114, null, 'Division', '63766', null, 'Salvador');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (69, 115, 116, 'Waywood', '8', null, 'Natal');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (70, 117, 118, 'Dahle', '0', null, 'Rio Branco');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (71, 119, 120, 'Mariners Cove', '968', null, 'Belém');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (72, 121, 122, 'Hazelcrest', '43', 'Terrace', 'Salvador');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (73, 123, 124, 'Mayfield', '99', 'Parkway', 'Florianópolis');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (74, 125, 126, 'Sage', '490', null, 'Belo Horizonte');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (75, 127, 128, 'Maple', '8162', null, 'Florianópolis');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (76, 129, 130, 'Atwood', '404', null, 'Belo Horizonte');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (77, 131, 132, 'Manitowish', '3', 'Park', 'Teresina');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (78, 133, 134, 'Dixon', '5', null, 'Salvador');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (79, 135, null, 'Basil', '240', null, 'Rio Branco');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (80, 136, 137, 'Schiller', '6', 'Park', 'Palmas');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (81, 138, 139, 'Packers', '664', null, 'Brasília');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (82, 140, 141, 'Ridgeview', '119', null, 'Rio Branco');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (83, 142, 143, 'Autumn Leaf', '894', null, 'São Paulo');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (84, 144, null, 'Mcguire', '65844', 'Park', 'Aracaju');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (85, 145, 146, 'Veith', '3225', null, 'Salvador');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (86, 147, 148, 'Talisman', '3', null, 'Florianópolis');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (87, 149, 150, 'Maple Wood', '7341', null, 'Boa Vista');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (88, 151, null, 'Mariners Cove', '0150', null, 'Belém');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (89, 152, 153, 'Hanover', '32039', null, 'Florianópolis');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (90, 154, 155, 'Garrison', '72', null, 'Belém');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (91, 156, 157, 'Summit', '485', null, 'São Paulo');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (92, 158, 159, 'Sullivan', '4620', null, 'Palmas');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (93, 160, null, 'Almo', '4723', null, 'Rio Branco');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (94, 161, null, 'Fisk', '14', 'Hill', 'Manaus');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (95, 162, 163, 'Heath', '4', null, 'Salvador');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (96, 164, null, 'Hoffman', '728', null, 'Fortaleza');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (97, 165, 166, 'Longview', '7767', 'Street', 'Belém');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (98, 167, null, 'Bay', '6639', null, 'Cuiabá');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (99, 168, 169, 'Sycamore', '55', null, 'Fortaleza');
insert into Workplace (id, phone1_id, phone2_id, street, street_number, complement, city) values (100, 170, null, 'Eastlawn', '23549', null, 'Porto Velho');
