name: Node.js CI - Frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Instalar dependências em Node.js ${{ matrix.node-version }}
      working-directory: frontend
      run: yarn

  cypress-run:
      runs-on: ubuntu-20.04

      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Cypress run
          uses: cypress-io/github-action@v4
          with:
            working-directory: frontend
            start: yarn start
            wait-on: 'http://localhost:3000'
