name: Node.js CI - Backend

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Selecionar versão Node.js ${{ matrix.node-version }}
      working-directory: backend
      run: npm ci
      
    - name: Executar Testes com Jest
      working-directory: backend
      run: npm test
